# Generated by Django 3.2.4 on 2021-08-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='date',
        ),
    ]
