# Generated by Django 3.2.4 on 2021-08-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM', '0004_auto_20210830_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
