# Generated by Django 3.2.4 on 2021-08-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM', '0005_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
