# Generated by Django 3.2.4 on 2021-08-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM', '0006_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
